/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      colors: {
        border:      'hsl(var(--border))',
        input:       'hsl(var(--input))',
        ring:        'hsl(var(--ring))',
        background:  'hsl(var(--background))',
        foreground:  'hsl(var(--foreground))',
        primary:     { DEFAULT: 'hsl(var(--primary))',     foreground: 'hsl(var(--primary-foreground))'  },
        secondary:   { DEFAULT: 'hsl(var(--secondary))',   foreground: 'hsl(var(--secondary-foreground))'},
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))'},
        muted:       { DEFAULT: 'hsl(var(--muted))',       foreground: 'hsl(var(--muted-foreground))'   },
        accent:      { DEFAULT: 'hsl(var(--accent))',      foreground: 'hsl(var(--accent-foreground))'  },
        popover:     { DEFAULT: 'hsl(var(--popover))',     foreground: 'hsl(var(--popover-foreground))' },
        card:        { DEFAULT: 'hsl(var(--card))',        foreground: 'hsl(var(--card-foreground))'    },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        mono: ['"Fira Code"', '"Fira Mono"', 'monospace'],
      },
      boxShadow: {
        'glass':  '0 8px 32px rgba(0, 0, 0, 0.08)',
        'lift':   '0 20px 60px rgba(0, 0, 0, 0.12)',
        'inner-top': 'inset 0 2px 4px rgba(0,0,0,0.04)',
      },
      backgroundImage: {
        'gradient-radial':  'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':   'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        'grid-pattern':     "radial-gradient(circle at 1px 1px, rgba(255,255,255,0.05) 1px, transparent 0)",
      },
      keyframes: {
        'accordion-down':  { from: { height: '0' },                       to: { height: 'var(--radix-accordion-content-height)' }},
        'accordion-up':    { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' }},
        'shimmer':         { '0%': { backgroundPosition: '-200% 0' },      '100%': { backgroundPosition: '200% 0' }},
        'float':           { '0%, 100%': { transform: 'translateY(0)' },   '50%': { transform: 'translateY(-8px)' }},
        'spin-slow':       { from: { transform: 'rotate(0deg)' },          to: { transform: 'rotate(360deg)' }},
        'fade-in-up':      { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' }},
        'slide-in-left':   { from: { opacity: '0', transform: 'translateX(-20px)' }, to: { opacity: '1', transform: 'translateX(0)' }},
        'pulse-glow':      { '0%, 100%': { boxShadow: '0 0 0 0 rgba(59,130,246,0)' }, '50%': { boxShadow: '0 0 0 8px rgba(59,130,246,0.15)' }},
        'count-up':        { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' }},
      },
      animation: {
        'accordion-down':  'accordion-down 0.2s ease-out',
        'accordion-up':    'accordion-up 0.2s ease-out',
        'shimmer':         'shimmer 1.5s infinite',
        'float':           'float 3s ease-in-out infinite',
        'spin-slow':       'spin-slow 8s linear infinite',
        'fade-in-up':      'fade-in-up 0.4s ease-out both',
        'slide-in-left':   'slide-in-left 0.4s ease-out both',
        'pulse-glow':      'pulse-glow 2s ease-in-out infinite',
        'count-up':        'count-up 0.4s ease-out both',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
